name: Dependency Review

on:
  pull_request_target: {}
  workflow_dispatch:
    inputs: {}

env:
  FOSSA_CLI_VERSION: '3.3.9'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: GitHub dependency vulnerability check
        uses: WillDaSilva/dependency-review-action@main
